
Vagrant.configure("2") do |config|

  #configure centos/7 operating system
  config.vm.box = "centos/7"

  #configure a web application 
  config.vm.define "web" do |web|
    web.vm.hostname="web"
    web.vm.network "private_network", ip: "192.168.33.10"
  end

  #configure a database application
  config.vm.define "db" do |db|
    db.vm.hostname="db"
    db.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  config.vm.usable_port_range =(8000..9000)



end
